# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:title/

# Setup
title:            fevargasmo
tagline:          'Perfil fevargasmo'
description:      'Estudiante Ingenieria de Sistemas - Universidad Nacional de Colombia'
url:              https://fevargasmo.github.io/
baseurl:          /

avatar: https://avatars1.githubusercontent.com/u/23062978?s=460&v=4


author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
